### ISSUE TITLE
how to enable noDefer?

### ISSUE THREAD

**Issue by tiye** [paul-nameless/nim-fswatch#4]
I'm using this library and experienced many times of slow responding. I thinks it's a problem in `libfswatch` but turned out it's a default behavior from according to https://github.com/emcrisostomo/fswatch/issues/230 . It sounds like we can change this behavior with a flag. Can I turn on `noDefer` in this library?

----

updates...

Seem it's making difference when I try [fsw_set_latency](https://github.com/paul-nameless/nim-fswatch/blob/5d62aae2c0028a010d1aaeccce30dd94e5f1a784/src/libfswatch.nim#L59)...

```nim
discard mon.handle.fsw_set_latency 0.2
```

**Comment by paul-nameless** [comment]
So setting latency resolved your problem?

**Comment by tiye** [comment]
I think so... it's quite responsive right now.

**Comment by paul-nameless** [comment]
Okay, I'll close it for now,. You are welcome to reopen the issue if needed)
